apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
spec:
  selector:
    matchLabels:
      app: document-service
  replicas: 1
  template:
    metadata:
      labels:
        app: document-service
    spec:
      volumes:
        - name: log
          emptyDir: {}
      containers:
        - name: document-service
          volumeMounts:
            - mountPath: /app/data/log
              name: log
          image: tuanloc/project:document-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8020
            - containerPort: 9020
          env:
            - name: SERVER_PORT
              value: "8020"
            - name: GRPC_PORT
              value: "9020"
            - name: GRPC_AUTH_SERVER
              value: auth-service-svc-2:9000
            - name: APPLICATION_NAME
              value: "@project.artifactId@"
            - name: MYSQL_DB_URL
              value: "jdbc:mysql://host.docker.internal:3306/tdtu_document_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
            - name: MYSQL_DB_USERNAME
              value: "root"
            - name: MYSQL_DB_PASSWORD
              value: "tyZnEfTQhn"
#  kubectl apply -f deploy.yml -n ingress-nginx
#  kubectl delete -f deploy.yml -n ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: document-service-svc-1
  labels:
    app: document-service
spec:
  type: NodePort
  selector:
    app: document-service
  ports:
    - protocol: "TCP"
      name: http
      port: 8020
      targetPort: 8020
---
apiVersion: v1
kind: Service
metadata:
  name: document-service-svc-2
  labels:
    app: document-service
spec:
  clusterIP: None
  selector:
    app: document-service
  ports:
    - port: 9020
      targetPort: 9020
