server:
  port: ${SERVER_PORT:8020}
  servlet:
    context-path: /document_service
grpc:
  server:
    port: ${GRPC_PORT:9020}
    auth_server: ${GRPC_AUTH_SERVER:localhost:9000}
spring:
  jpa:
    open-in-view: false
  application:
    name: ${APPLICATION_NAME:@project.artifactId@}
  security:
    user:
      name: user
      password: E2$s3U07L#wu
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
security:
  enable: false
mysql:
  url: ${MYSQL_DB_URL:jdbc:mysql://localhost:3306/tdtu_document_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
  username: ${MYSQL_DB_USERNAME:root}
  password: ${MYSQL_DB_PASSWORD:tyZnEfTQhn}
  driver_class_name: com.mysql.cj.jdbc.Driver
  ddl_auto: none
  dialect: org.hibernate.dialect.MySQLDialect
  show_sql: false
management:
  tracing:
    sampling:
      probability: '1.0'
